# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            YuSpace
tagline:          'Tech notes'
description:      'Some random programming and technical comments from <a href="https://www.mit.edu/~wangyu">Yu</a>.'
url:              http://bigeyex.github.io
baseurl:          /

author:
  name:           'Yu Wang'
  url:            https://www.mit.edu/~wangyu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bigeyex


# Used Gems
gems:
- jekyll-gist
- jekyll-paginate
